# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f831910be3c8717e7f4f4fc2dcbcc7215bc41edbec33fd0a808e508cdbd64ba2bc4c66991e6ad0d507e31af7c18412469a29ba463d3b418d3615eb1d063d366a

test:
  secret_key_base: 41d1e6ce3fb075c160983c4576730283fcbfe53ebf2648ebb9e8dd3818e17c0131236732ecca09f34a87a93e42934fa5c9a68ad12968f079f6fcf47e8085fd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
